data=as.character(Sys.Date())
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//tvn//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//tvn//wybory//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//wp//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//newsweek//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//tvp//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//onet//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//gazeta//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//onet//wybory//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//twitter//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//twitter//duda//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//twitter//jarubas//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//twitter//komorowski//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//twitter//kukiz//',as.character(data))
dir.create(nazwa)
nazwa=stri_paste('D://szkola//R i Big Data//projekt 1//twitter//ogorek//',as.character(data))
dir.create(nazwa)
