---
title: "Analiza twittów na temat zbliżającego się zaćmienia słońca"
author: "Marta Sommer"
date: "Wednesday, March 18, 2015"
output: html_document
---


```{r, warning=FALSE, message=FALSE}
library("streamR")
library("RCurl")
library("ROAuth")
library("stringi")
library("tm")
library("wordcloud")
```


```{r, echo=FALSE, eval=FALSE, warning=FALSE, message=FALSE}

# pobieranie danych z Twittera na temat sun eclipse:

requestURL <- "https://api.twitter.com/oauth/request_token"
accessURL <- "https://api.twitter.com/oauth/access_token"
authURL <- "https://api.twitter.com/oauth/authorize"
consumerKey <- "xxx"
consumerSecret <- "xxx"

my_oauth <- OAuthFactory$new(consumerKey=consumerKey,
                             consumerSecret=consumerSecret, requestURL=requestURL,
                             accessURL=accessURL, authURL=authURL)
my_oauth$handshake(cainfo = system.file("CurlSSL", "cacert.pem", package = "RCurl"))

filterStream(file="C:\\Users\\Marta\\Dropbox\\R_i_Big_Data\\prace_domowe\\pd2\\eclipse2.json",
             track="sun eclipse", 
             timeout=45*60, oauth=my_oauth) 
```


```{r}

# wczytanie dwoch plikow z danymi:

dane1 <- parseTweets("C:\\Users\\Marta\\Dropbox\\R_i_Big_Data\\prace_domowe\\pd2\\eclipse.json", 
                    simplify=FALSE, verbose=TRUE)
dane2 <- parseTweets("C:\\Users\\Marta\\Dropbox\\R_i_Big_Data\\prace_domowe\\pd2\\eclipse2.json", 
                     simplify=FALSE, verbose=TRUE)
dane11 <- unique(dane1$text)
dane22 <- unique(dane2$text)
dane <- c(dane11, dane22)

# slownik:

stopwords <- c("a", "about", "above", "above", "across", "after", "afterwards", 
               "again", "against", "all", "almost", "alone", "along", "already", 
               "also","although","always","am","among", "amongst", "amoungst", 
               "amount",  "an", "and", "another", "any","anyhow","anyone","anything",
               "anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", 
               "because","become","becomes", "becoming", "been", "before", "beforehand", 
               "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", 
               "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", 
               "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", 
               "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", 
               "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", 
               "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", 
               "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", 
               "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", 
               "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", 
               "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", 
               "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", 
               "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", 
               "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", 
               "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", 
               "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", 
               "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", 
               "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", 
               "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", 
               "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", 
               "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", 
               "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", 
               "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", 
               "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though", "three", 
               "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", 
               "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", 
               "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", 
               "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", 
               "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", 
               "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the", 
               "i'm", "you're", "he's", "she's", "it's", "we're", "they're", "i've", "you've", "we've", 
               "they've", "won't", "aren't", "isn't", "wasn't", "weren't", "haven't", "hasn't")

# wyrzucenie niepotrzebnych slow (stron internetowych, nazw uzytkownikow...)

wszystko <- stri_paste(dane, collapse=" ")
wszystko <- stri_trans_tolower(wszystko)

bez_linkow <- stri_replace_all_regex(wszystko, "http:.*?[\\s]", " ")
bez_uzytkownikow <- stri_replace_all_regex(bez_linkow, "@.*?[\\s]", " ")
slowa <- stri_trans_tolower(unlist(stri_extract_all_words(bez_uzytkownikow)))

dobreslowa <- slowa[(!slowa %in% stopwords)]
dobreslowa2 <- stri_replace_all_regex(dobreslowa, "\\p{P}.*?[//s]", "")
dobreslowa3 <- stri_replace_all_fixed(dobreslowa2, "fri", "friday")
dobreslowa4 <- dobreslowa3[-which(dobreslowa3 %in% c("iss", "rt", "gt", "amp"))]

t <- table(dobreslowa4)
```

Wykres najczęściej występujących słów wśród twittów:

```{r}
wordcloud(names(t),  t, scale=c(5,0.5), random.order=F, colors="black")

d <- na.omit(unlist(stri_extract_all_words(stri_trans_tolower(c(dane1$location, dane2$location)))))
d <- d[!(d %in% stopwords)]
d <- d[!d %in% c("west", "north", "south", "east", "northern", "southern", 'eastern', "western")]
d[d %in% c("ny", "nyc", "york", "new")] <- "new york"
d <- d[!(d %in% c("ca", "st"))] 

tt <- table(d)

```

Wykres miejsc, z których pisali autorzy twittów:

```{r}

wordcloud(names(tt),  tt, scale=c(5,0.5), random.order=F, colors="black", 
          min.freq=2)

```


