---
title: "Kodowanie artykułów na portalu wp.pl"
author: "Marcin Kosinski"
date: "Marzec 11, 2015"
output:
  html_document:
    theme: readable
    highlight: kate
    fig_width: 17
    fig_height: 10
    toc: true
    toc_depth: 3
    keep_md: true
---

```{r, echo=FALSE}
library(knitr)
opts_chunk$set(comment="", message = FALSE, warning = FALSE,
               tidy.opts=list(keep.blank.line=TRUE, width.cutoff=150),options(width=150), cache=TRUE)
```


# Wczytanie pakietu i pobranie listy artykułów

```{r}
library(rvest)
library(magrittr)
library(stringr)

wp <- html("http://www.wp.pl/")
artykuly <- html_nodes(wp,"div.sArt a") %>%
    html_attrs()


linki_do_artykulow <- lapply( artykuly, function( element ){
    element["href"]
})
    artykuly <- linki_do_artykulow # zeby moc skopiowac kod
 encodings <- lapply( artykuly, function(element){
     
     # for( element in artykuly ){
     landing_page_artykulu <- html(element[1])
     charset <- html_nodes( landing_page_artykulu ,"meta[http-equiv=Content-Type]") %>% 
         html_attr("content") 
          
     if ( length( charset > 0 )){
          encoding <- str_split( string = charset, pattern = "=" )[[1]][2]
          encoding
     }else{ #charset nie jest spojny na wszystkich stronach
          encoding <- html_nodes( landing_page_artykulu , "meta[charset]" ) %>% 
              html_attrs( )   
          encoding[[1]]
     }
     
     
     
 })


encodings <- tolower(unlist(encodings))

```

# Jakie są kodowania dla artykułów ze strony głównej wp.pl

```{r}
table(encodings)
```


# Dla ilu artykułów kodowanie było wprowadzone inaczej niż poprzez `meta http-equiv`


```{r}
table(names(encodings))
# puste to standardowy sposób
# o nazwie "charset" to archaizm
```


